name: CI Validation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/common-tests.yaml
